### ISSUE TITLE
OpenVSP Workshop 2019 slides

### ISSUE THREAD

**Issue by ghost** [Czarified/CSLM#16]
- http://openvsp.org/wiki/doku.php?id=workshop2019
  - «Git Version control of VSP models and libraries» - http://openvsp.org/wiki/lib/exe/fetch.php?media=workshop19:vsp-ws19_git_version_control.pdf

**Comment by Czarified** [comment]
Thanks! I'll look into this!

**Comment by Czarified** [comment]
VSP model is included in each commit and changes can be seen as file is versioned. I believe this is all handled automatically by git and OpenVSP's architecture, but I'll leave this open for now.

**Comment by ghost** [comment]
FTR, *OpenVSP* `3.19.0` released few days ago with some new features such as *«Generic XSec Editor»* (highlighted in «[ESAero AFRL SBIR (PDF)](http://openvsp.org/wiki/lib/exe/fetch.php?media=workshop19:afrl_openvsp_presentation.pdf)» presentation slides)

- http://openvsp.org/blogs/announcements/2019/11/09/openvsp-3-19-0-released
